d.github={...
	'github' 'octsympy' '0.0.3' 'https://github.com/cbm755/octsympy' '' {...
		'syms' 'run_unit_tests' 'run_octave_tests' 'python_sympy_cmd' 'python_cmd' 'octsympy_reset' 'octsympy_config' 'fibonacci' 'evalpy' 'bernoulli' '@logical' '@s' '@symfun'} {...
		'';
		} 'Adds symbolic calculation features to GNU Octave.';

	'github' 'go-sqlite' '1' 'https://github.com/markuman/go-sqlite' '' {...
'insert','runsqlscript','sqldump','sqlite'} {...
		' ';
		} 'SQLite 3 Database Toolbox';

	'github' 'instrument-control' '0.2.1' 'https://github.com/dac922/octave-instrument-control' 'GPLv3+' {...
'serial','srl_read','srl_write','srl_baudrate','srl_bytesize','srl_flush','srl_parity','srl_stopbits','srl_timeout','srl_close','i2c','i2c_addr','i2c_read','i2c_write','i2c_close','parallel','pp_datadir','pp_data','pp_ctrl','pp_stat','pp_close','tcp','tcp_read','tcp_write','tcp_timeout','tcp_close','usbtmc','usbtmc_read','usbtmc_write','usbtmc_close','gpib','gpib_read','gpib_write','gpib_timeout','gpib_close','fopen','fclose','fwrite','fprintf','fscanf','spoll','trigger','clrdevice','vxi11','vxi11_read','vxi11_write','vxi11_close'} {...
		' octave (>= 3.2.0)';
		} 'Low level I/O functions for serial, i2c, parallel, tcp, gpib, vxi11 and usbtmc interfaces.';

	};
